# Generated by Django 5.0.6 on 2024-11-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catehories',
            new_name='category',
        ),
    ]
